---
title: HGR Immobilienmanagement
timezone: UTC
collections:
  team:
    title: Team
    output: true
    portrait: image
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: team
  values:
    layout: team
email: info@nikitasarejko.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: nnnnikita
github_username: nikitasarejko
theme: minima
plugins:
- jekyll-feed
