---
title: HGR Immobilienmanagement
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  people:
    title: People
    output: true
    portrait: image

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: people
  values:
    layout: default
email: info@nikitasarejko.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: nnnnikita
github_username: nikitasarejko
theme: minima
plugins:
- jekyll-feed
