---
title: HGR Immobilienmanagement
timezone: UTC
collections:
  objekte:
    title: Objekte
    output: true
  posts:
    title: Posts
    output: true
  stellen:
    title: Stellen
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: team
  values:
    layout: team
- scope:
    path: ''
    type: objekte
  values:
    layout: objekte
- scope:
    path: ''
    type: stellen
  values:
    layout: karriere
email: info@nikitasarejko.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: 
github_username: nikitasarejko
theme: minima
plugins:
- jekyll-feed
